plugins {
    id 'com.android.application'
}

android {
    namespace 'com.minimalserifclock.widget'
    compileSdk 36

    defaultConfig {
        applicationId 'com.minimalserifclock.widget'
        minSdk 26
        targetSdk 36
        versionCode 3
        versionName '1.2'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
